fix: release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,6 +35,21 @@ jobs:
       - name: Create venv
         run: uv venv
 
+      - name: Update version
+        run: |
+          PYPROJECT_VERSION=$(uv version --short)
+          GIT_TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
+          echo "pyproject.toml Version: $PYPROJECT_VERSION"
+          echo "Git Tag Version (without 'v'): $GIT_TAG_VERSION"
+          
+          if [ "$PYPROJECT_VERSION" != "$GIT_TAG_VERSION" ]; then
+            echo "::error file=pyproject.toml,line=1::Version mismatch detected! Tag ($GIT_TAG_VERSION) does not match pyproject.toml ($PYPROJECT_VERSION)."
+            exit 1
+          fi
+          
+          echo "✅ Version check passed: $PYPROJECT_VERSION"
+           
+
       - name: Build sdist and wheel
         run: uv build
 
@@ -57,6 +72,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/etl_framework_core-${{ github.ref_name }}-py3-none-any.whl
-          asset_name: etl_framework_core-${{ github.ref_name }}-py3-none-any.whl
+          asset_path: ./dist/etl_framework_core-${{ env.GIT_TAG_VERSION }}-py3-none-any.whl
+          asset_name: etl_framework_core-${{ env.GIT_TAG_VERSION }}-py3-none-any.whl
           asset_content_type: application/octet-stream
